# Generated by Django 2.1.8 on 2019-05-15 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0002_score_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='genreId',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
    ]
