# Generated by Django 2.1.8 on 2019-05-16 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_score_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='genres',
            field=models.ManyToManyField(blank=True, related_name='movie', to='movies.Genre'),
        ),
    ]
